// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3jEFAe8JNN8_T1zXLXmWJx9IiQelLOns',
    appId: '1:416381599623:web:97a581a96c93d3f0555d22',
    messagingSenderId: '416381599623',
    projectId: 'campus-lost-found-1af54',
    authDomain: 'campus-lost-found-1af54.firebaseapp.com',
    storageBucket: 'campus-lost-found-1af54.firebasestorage.app',
    measurementId: 'G-6290PCM5FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqY8KjR7oJR3hULCaWkZDrVv7dELeQzRE',
    appId: '1:416381599623:android:2f69956fa5372cb2555d22',
    messagingSenderId: '416381599623',
    projectId: 'campus-lost-found-1af54',
    storageBucket: 'campus-lost-found-1af54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD94KN4MO_m3ofKQ9C1S_1rDWikdpuqoLs',
    appId: '1:416381599623:ios:56b0630f687227ef555d22',
    messagingSenderId: '416381599623',
    projectId: 'campus-lost-found-1af54',
    storageBucket: 'campus-lost-found-1af54.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD94KN4MO_m3ofKQ9C1S_1rDWikdpuqoLs',
    appId: '1:416381599623:ios:56b0630f687227ef555d22',
    messagingSenderId: '416381599623',
    projectId: 'campus-lost-found-1af54',
    storageBucket: 'campus-lost-found-1af54.firebasestorage.app',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3jEFAe8JNN8_T1zXLXmWJx9IiQelLOns',
    appId: '1:416381599623:web:aca9e49e6e0fd7c9555d22',
    messagingSenderId: '416381599623',
    projectId: 'campus-lost-found-1af54',
    authDomain: 'campus-lost-found-1af54.firebaseapp.com',
    storageBucket: 'campus-lost-found-1af54.firebasestorage.app',
    measurementId: 'G-QH7GSD0M6C',
  );
}
